pipeline{
 agent any
  stages
  {
     stage("build")
    {
     steps{
      sh 'docker build -t tong .'
      sh 'docker run -dp 3000:3000 tong'
      sh 'docker container ls'
      sh 'docker ps'
      sh 'ls'
      sh 'curl http://localhost:2000'
      sh 'docker ps'
      sh 'docker run hello-world'
      sh 'docker ps'
      sh 'docker ps'
      
     }
    }
  }
}
