pipeline{
 agent any
  stages
  {
     stage("build")
    {
     steps{
      sh 'docker build -t tong .'
      sh 'docker run -dp 3000:3000 tong'
      sh 'docker container ls && curl http://localhost:3000'
     }
    }
  }
}
